stages:
  - build
  - test
  - deploy


composer: 
  stage: build
  image: lorisleiva/laravel-docker:latest
  script: 
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.exemple .env
    - php artisan key:generate
  cache: 
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths: 
      - vendor/
      - .env
    artifacts:
      expire_in: 1 month
      paths:
        - node_modules/
        - public/css/
        - public/js/


phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app
  
